export const lightColors = {
    UNFOCUSED_TAB_BAR: '#999999',
    FOCUSED_TAB_BAR: '#ff7300',
    PRIMARY_COLOR: '#ff7300',
    SECONDARY_COLOR: '#fd475d',
    SALEOFF_COLOR: '#F7A34A',
    PRICE_TAG_COLOR: '#c52c29',
    PRICE_ORIGIN_COLOR: '#999999',
    LIGHT_BORDER: '#f5f5f5',
    DARK_BORDER: '#999999',
    GRAY_INPUT: '#f8f8f8',
    GRAY_BOLD: '#dcdcdc',
    INACTIVE_COLOR: '#EBEBE4',
    PINK_BG: '#fcf6f4',
    PINK_BG_DARK: '#feedec',
    PRODUCT_LABEL: '#19124f',
    YELLOW_STAR: '#ffbc59',
    BLUE_SKY: '#2792ce',
    DIVIDER_COLOR: '#f1f1f1',
    FOCUS_BUTTON: '#ff3945',
    SUCCESS_COLOR: '#22be79',
    ERROR_COLOR: '#ed0505',
};

export const darkColors = {
    UNFOCUSED_TAB_BAR: '#999999',
    FOCUSED_TAB_BAR: '#d1551f',
    PRIMARY_COLOR: '#ff7300',
    SECONDARY_COLOR: '#fd475d',
    SALEOFF_COLOR: '#F7A34A',
    PRICE_TAG_COLOR: '#c52c29',
    PRICE_ORIGIN_COLOR: '#dcdcdc',
    LIGHT_BORDER: '#dcdcdc',
    DARK_BORDER: '#999999',
    GRAY_INPUT: '#f2f2f2', //old color,
    GRAY_BOLD: '#dcdcdc',
    INACTIVE_COLOR: '#EBEBE4',
    PINK_BG: '#feedec',
    PINK_BG_DARK: '#feedec',
    PRODUCT_LABEL: '#19124f',
    YELLOW_STAR: '#ffbc59',
    BLUE_SKY: '#2792ce',
    DIVIDER_COLOR: '#f1f1f1',
    FOCUS_BUTTON: '#ff3945',
    SUCCESS_COLOR: '#22be79',
};
